spring:
  application:
    name: emergency-service
  datasource:
    url: jdbc:postgresql://localhost:5432/emergency_db?createDatabaseIfNotExist=true
    username: ur-username
    password: ur-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 8085

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  defaultZone:
    url: http://localhost:8761/eureka/


